/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ColoringCategory = IDL.Variant({
  'characters' : IDL.Null,
  'animals' : IDL.Null,
  'objects' : IDL.Null,
});
export const AgeGroup = IDL.Variant({
  'threeToFive' : IDL.Null,
  'nineToTwelve' : IDL.Null,
  'thirteenToFifteen' : IDL.Null,
  'sixToEight' : IDL.Null,
});
export const ColoringTemplateWithData = IDL.Record({
  'id' : IDL.Text,
  'template' : ExternalBlob,
  'category' : ColoringCategory,
  'ageGroup' : AgeGroup,
});
export const Language = IDL.Variant({
  'portuguese' : IDL.Null,
  'japanese' : IDL.Null,
  'chinese' : IDL.Null,
  'turkish' : IDL.Null,
  'italian' : IDL.Null,
  'spanish' : IDL.Null,
  'german' : IDL.Null,
  'french' : IDL.Null,
  'russian' : IDL.Null,
  'english' : IDL.Null,
});
export const SimpleGame = IDL.Record({
  'name' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'ageGroup' : AgeGroup,
});
export const LocalizedText = IDL.Record({
  'portuguese' : IDL.Text,
  'japanese' : IDL.Text,
  'chinese' : IDL.Text,
  'turkish' : IDL.Text,
  'italian' : IDL.Text,
  'spanish' : IDL.Text,
  'german' : IDL.Text,
  'french' : IDL.Text,
  'russian' : IDL.Text,
  'english' : IDL.Text,
});
export const LogicPuzzle = IDL.Record({
  'question' : LocalizedText,
  'difficulty' : IDL.Nat,
  'answer' : LocalizedText,
});
export const MemoryGame = IDL.Record({
  'patterns' : IDL.Text,
  'difficulty' : IDL.Nat,
  'language' : Language,
});
export const ProblemSolving = IDL.Record({
  'correctOption' : LocalizedText,
  'scenario' : LocalizedText,
  'options' : IDL.Vec(LocalizedText),
});
export const SimpleQuestion = IDL.Record({
  'question' : IDL.Opt(IDL.Text),
  'correctAnswer' : IDL.Opt(IDL.Text),
  'options' : IDL.Vec(IDL.Text),
});
export const VisualRecognition = IDL.Record({
  'differences' : IDL.Nat,
  'language' : Language,
  'imageId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'getAllColoringTemplates' : IDL.Func(
      [],
      [IDL.Vec(ColoringTemplateWithData)],
      ['query'],
    ),
  'getColoringTemplateById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ColoringTemplateWithData)],
      ['query'],
    ),
  'getColoringTemplatesByAgeGroup' : IDL.Func(
      [AgeGroup],
      [IDL.Vec(ColoringTemplateWithData)],
      ['query'],
    ),
  'getColoringTemplatesByCategory' : IDL.Func(
      [ColoringCategory],
      [IDL.Vec(ColoringTemplateWithData)],
      ['query'],
    ),
  'getEncouragementMessage' : IDL.Func(
      [IDL.Nat, Language],
      [IDL.Text],
      ['query'],
    ),
  'getGames' : IDL.Func([IDL.Text, Language], [IDL.Vec(SimpleGame)], ['query']),
  'getLogicPuzzles' : IDL.Func([IDL.Text], [IDL.Vec(LogicPuzzle)], ['query']),
  'getMemoryGames' : IDL.Func([IDL.Text], [IDL.Vec(MemoryGame)], ['query']),
  'getProblemSolvingTasks' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProblemSolving)],
      ['query'],
    ),
  'getQuizQuestions' : IDL.Func(
      [IDL.Text, Language],
      [IDL.Vec(SimpleQuestion)],
      ['query'],
    ),
  'getRandomSoundByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ExternalBlob)],
      ['query'],
    ),
  'getSoundByName' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], ['query']),
  'getSoundCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getSoundsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob))],
      ['query'],
    ),
  'getVisualRecognitionTasks' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(VisualRecognition)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ColoringCategory = IDL.Variant({
    'characters' : IDL.Null,
    'animals' : IDL.Null,
    'objects' : IDL.Null,
  });
  const AgeGroup = IDL.Variant({
    'threeToFive' : IDL.Null,
    'nineToTwelve' : IDL.Null,
    'thirteenToFifteen' : IDL.Null,
    'sixToEight' : IDL.Null,
  });
  const ColoringTemplateWithData = IDL.Record({
    'id' : IDL.Text,
    'template' : ExternalBlob,
    'category' : ColoringCategory,
    'ageGroup' : AgeGroup,
  });
  const Language = IDL.Variant({
    'portuguese' : IDL.Null,
    'japanese' : IDL.Null,
    'chinese' : IDL.Null,
    'turkish' : IDL.Null,
    'italian' : IDL.Null,
    'spanish' : IDL.Null,
    'german' : IDL.Null,
    'french' : IDL.Null,
    'russian' : IDL.Null,
    'english' : IDL.Null,
  });
  const SimpleGame = IDL.Record({
    'name' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'ageGroup' : AgeGroup,
  });
  const LocalizedText = IDL.Record({
    'portuguese' : IDL.Text,
    'japanese' : IDL.Text,
    'chinese' : IDL.Text,
    'turkish' : IDL.Text,
    'italian' : IDL.Text,
    'spanish' : IDL.Text,
    'german' : IDL.Text,
    'french' : IDL.Text,
    'russian' : IDL.Text,
    'english' : IDL.Text,
  });
  const LogicPuzzle = IDL.Record({
    'question' : LocalizedText,
    'difficulty' : IDL.Nat,
    'answer' : LocalizedText,
  });
  const MemoryGame = IDL.Record({
    'patterns' : IDL.Text,
    'difficulty' : IDL.Nat,
    'language' : Language,
  });
  const ProblemSolving = IDL.Record({
    'correctOption' : LocalizedText,
    'scenario' : LocalizedText,
    'options' : IDL.Vec(LocalizedText),
  });
  const SimpleQuestion = IDL.Record({
    'question' : IDL.Opt(IDL.Text),
    'correctAnswer' : IDL.Opt(IDL.Text),
    'options' : IDL.Vec(IDL.Text),
  });
  const VisualRecognition = IDL.Record({
    'differences' : IDL.Nat,
    'language' : Language,
    'imageId' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'getAllColoringTemplates' : IDL.Func(
        [],
        [IDL.Vec(ColoringTemplateWithData)],
        ['query'],
      ),
    'getColoringTemplateById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ColoringTemplateWithData)],
        ['query'],
      ),
    'getColoringTemplatesByAgeGroup' : IDL.Func(
        [AgeGroup],
        [IDL.Vec(ColoringTemplateWithData)],
        ['query'],
      ),
    'getColoringTemplatesByCategory' : IDL.Func(
        [ColoringCategory],
        [IDL.Vec(ColoringTemplateWithData)],
        ['query'],
      ),
    'getEncouragementMessage' : IDL.Func(
        [IDL.Nat, Language],
        [IDL.Text],
        ['query'],
      ),
    'getGames' : IDL.Func(
        [IDL.Text, Language],
        [IDL.Vec(SimpleGame)],
        ['query'],
      ),
    'getLogicPuzzles' : IDL.Func([IDL.Text], [IDL.Vec(LogicPuzzle)], ['query']),
    'getMemoryGames' : IDL.Func([IDL.Text], [IDL.Vec(MemoryGame)], ['query']),
    'getProblemSolvingTasks' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProblemSolving)],
        ['query'],
      ),
    'getQuizQuestions' : IDL.Func(
        [IDL.Text, Language],
        [IDL.Vec(SimpleQuestion)],
        ['query'],
      ),
    'getRandomSoundByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ExternalBlob)],
        ['query'],
      ),
    'getSoundByName' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], ['query']),
    'getSoundCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getSoundsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob))],
        ['query'],
      ),
    'getVisualRecognitionTasks' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(VisualRecognition)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };