/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AgeGroup = { 'threeToFive' : null } |
  { 'nineToTwelve' : null } |
  { 'thirteenToFifteen' : null } |
  { 'sixToEight' : null };
export type ColoringCategory = { 'characters' : null } |
  { 'animals' : null } |
  { 'objects' : null };
export interface ColoringTemplateWithData {
  'id' : string,
  'template' : ExternalBlob,
  'category' : ColoringCategory,
  'ageGroup' : AgeGroup,
}
export type ExternalBlob = Uint8Array;
export type Language = { 'portuguese' : null } |
  { 'japanese' : null } |
  { 'chinese' : null } |
  { 'turkish' : null } |
  { 'italian' : null } |
  { 'spanish' : null } |
  { 'german' : null } |
  { 'french' : null } |
  { 'russian' : null } |
  { 'english' : null };
export interface LocalizedText {
  'portuguese' : string,
  'japanese' : string,
  'chinese' : string,
  'turkish' : string,
  'italian' : string,
  'spanish' : string,
  'german' : string,
  'french' : string,
  'russian' : string,
  'english' : string,
}
export interface LogicPuzzle {
  'question' : LocalizedText,
  'difficulty' : bigint,
  'answer' : LocalizedText,
}
export interface MemoryGame {
  'patterns' : string,
  'difficulty' : bigint,
  'language' : Language,
}
export interface ProblemSolving {
  'correctOption' : LocalizedText,
  'scenario' : LocalizedText,
  'options' : Array<LocalizedText>,
}
export interface SimpleGame {
  'name' : [] | [string],
  'description' : [] | [string],
  'ageGroup' : AgeGroup,
}
export interface SimpleQuestion {
  'question' : [] | [string],
  'correctAnswer' : [] | [string],
  'options' : Array<string>,
}
export interface VisualRecognition {
  'differences' : bigint,
  'language' : Language,
  'imageId' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'getAllColoringTemplates' : ActorMethod<[], Array<ColoringTemplateWithData>>,
  'getColoringTemplateById' : ActorMethod<
    [string],
    [] | [ColoringTemplateWithData]
  >,
  'getColoringTemplatesByAgeGroup' : ActorMethod<
    [AgeGroup],
    Array<ColoringTemplateWithData>
  >,
  'getColoringTemplatesByCategory' : ActorMethod<
    [ColoringCategory],
    Array<ColoringTemplateWithData>
  >,
  'getEncouragementMessage' : ActorMethod<[bigint, Language], string>,
  'getGames' : ActorMethod<[string, Language], Array<SimpleGame>>,
  'getLogicPuzzles' : ActorMethod<[string], Array<LogicPuzzle>>,
  'getMemoryGames' : ActorMethod<[string], Array<MemoryGame>>,
  'getProblemSolvingTasks' : ActorMethod<[string], Array<ProblemSolving>>,
  'getQuizQuestions' : ActorMethod<[string, Language], Array<SimpleQuestion>>,
  'getRandomSoundByCategory' : ActorMethod<[string], [] | [ExternalBlob]>,
  'getSoundByName' : ActorMethod<[string], [] | [ExternalBlob]>,
  'getSoundCategories' : ActorMethod<[], Array<string>>,
  'getSoundsByCategory' : ActorMethod<[string], Array<[string, ExternalBlob]>>,
  'getVisualRecognitionTasks' : ActorMethod<[string], Array<VisualRecognition>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];