// Item pools for Sorting/Classification game with expanded variety per age group

export type SortingItem = {
  id: string;
  name: string;
  category: string;
  emoji: string;
};

export type AgeGroupKey = '3-5' | '6-8' | '9-12' | '13-15';

// Category sets per age group (fixed, matching current behavior)
export const CATEGORIES_BY_AGE: Record<AgeGroupKey, string[]> = {
  '3-5': ['fruit', 'vegetable'],
  '6-8': ['fruit', 'vegetable', 'animal'],
  '9-12': ['fruit', 'vegetable', 'animal', 'vehicle'],
  '13-15': ['fruit', 'vegetable', 'animal', 'vehicle', 'object'],
};

// Expanded item pools per age group
export const ITEM_POOLS_BY_AGE: Record<AgeGroupKey, SortingItem[]> = {
  '3-5': [
    // Fruits
    { id: '3-5-fruit-1', name: 'Apple', category: 'fruit', emoji: '🍎' },
    { id: '3-5-fruit-2', name: 'Banana', category: 'fruit', emoji: '🍌' },
    { id: '3-5-fruit-3', name: 'Orange', category: 'fruit', emoji: '🍊' },
    { id: '3-5-fruit-4', name: 'Grapes', category: 'fruit', emoji: '🍇' },
    { id: '3-5-fruit-5', name: 'Strawberry', category: 'fruit', emoji: '🍓' },
    { id: '3-5-fruit-6', name: 'Watermelon', category: 'fruit', emoji: '🍉' },
    { id: '3-5-fruit-7', name: 'Pear', category: 'fruit', emoji: '🍐' },
    { id: '3-5-fruit-8', name: 'Peach', category: 'fruit', emoji: '🍑' },
    { id: '3-5-fruit-9', name: 'Cherries', category: 'fruit', emoji: '🍒' },
    { id: '3-5-fruit-10', name: 'Lemon', category: 'fruit', emoji: '🍋' },
    // Vegetables
    { id: '3-5-veg-1', name: 'Carrot', category: 'vegetable', emoji: '🥕' },
    { id: '3-5-veg-2', name: 'Broccoli', category: 'vegetable', emoji: '🥦' },
    { id: '3-5-veg-3', name: 'Tomato', category: 'vegetable', emoji: '🍅' },
    { id: '3-5-veg-4', name: 'Corn', category: 'vegetable', emoji: '🌽' },
    { id: '3-5-veg-5', name: 'Cucumber', category: 'vegetable', emoji: '🥒' },
    { id: '3-5-veg-6', name: 'Pepper', category: 'vegetable', emoji: '🫑' },
    { id: '3-5-veg-7', name: 'Potato', category: 'vegetable', emoji: '🥔' },
    { id: '3-5-veg-8', name: 'Eggplant', category: 'vegetable', emoji: '🍆' },
    { id: '3-5-veg-9', name: 'Lettuce', category: 'vegetable', emoji: '🥬' },
    { id: '3-5-veg-10', name: 'Onion', category: 'vegetable', emoji: '🧅' },
  ],
  '6-8': [
    // Fruits
    { id: '6-8-fruit-1', name: 'Apple', category: 'fruit', emoji: '🍎' },
    { id: '6-8-fruit-2', name: 'Banana', category: 'fruit', emoji: '🍌' },
    { id: '6-8-fruit-3', name: 'Orange', category: 'fruit', emoji: '🍊' },
    { id: '6-8-fruit-4', name: 'Grapes', category: 'fruit', emoji: '🍇' },
    { id: '6-8-fruit-5', name: 'Strawberry', category: 'fruit', emoji: '🍓' },
    { id: '6-8-fruit-6', name: 'Watermelon', category: 'fruit', emoji: '🍉' },
    { id: '6-8-fruit-7', name: 'Pineapple', category: 'fruit', emoji: '🍍' },
    { id: '6-8-fruit-8', name: 'Mango', category: 'fruit', emoji: '🥭' },
    { id: '6-8-fruit-9', name: 'Kiwi', category: 'fruit', emoji: '🥝' },
    { id: '6-8-fruit-10', name: 'Blueberries', category: 'fruit', emoji: '🫐' },
    // Vegetables
    { id: '6-8-veg-1', name: 'Carrot', category: 'vegetable', emoji: '🥕' },
    { id: '6-8-veg-2', name: 'Broccoli', category: 'vegetable', emoji: '🥦' },
    { id: '6-8-veg-3', name: 'Tomato', category: 'vegetable', emoji: '🍅' },
    { id: '6-8-veg-4', name: 'Corn', category: 'vegetable', emoji: '🌽' },
    { id: '6-8-veg-5', name: 'Cucumber', category: 'vegetable', emoji: '🥒' },
    { id: '6-8-veg-6', name: 'Pepper', category: 'vegetable', emoji: '🫑' },
    { id: '6-8-veg-7', name: 'Mushroom', category: 'vegetable', emoji: '🍄' },
    { id: '6-8-veg-8', name: 'Pumpkin', category: 'vegetable', emoji: '🎃' },
    { id: '6-8-veg-9', name: 'Garlic', category: 'vegetable', emoji: '🧄' },
    { id: '6-8-veg-10', name: 'Radish', category: 'vegetable', emoji: '🥗' },
    // Animals
    { id: '6-8-animal-1', name: 'Dog', category: 'animal', emoji: '🐕' },
    { id: '6-8-animal-2', name: 'Cat', category: 'animal', emoji: '🐈' },
    { id: '6-8-animal-3', name: 'Rabbit', category: 'animal', emoji: '🐰' },
    { id: '6-8-animal-4', name: 'Bird', category: 'animal', emoji: '🐦' },
    { id: '6-8-animal-5', name: 'Fish', category: 'animal', emoji: '🐟' },
    { id: '6-8-animal-6', name: 'Elephant', category: 'animal', emoji: '🐘' },
    { id: '6-8-animal-7', name: 'Lion', category: 'animal', emoji: '🦁' },
    { id: '6-8-animal-8', name: 'Monkey', category: 'animal', emoji: '🐵' },
    { id: '6-8-animal-9', name: 'Panda', category: 'animal', emoji: '🐼' },
    { id: '6-8-animal-10', name: 'Penguin', category: 'animal', emoji: '🐧' },
  ],
  '9-12': [
    // Fruits
    { id: '9-12-fruit-1', name: 'Apple', category: 'fruit', emoji: '🍎' },
    { id: '9-12-fruit-2', name: 'Banana', category: 'fruit', emoji: '🍌' },
    { id: '9-12-fruit-3', name: 'Orange', category: 'fruit', emoji: '🍊' },
    { id: '9-12-fruit-4', name: 'Grapes', category: 'fruit', emoji: '🍇' },
    { id: '9-12-fruit-5', name: 'Strawberry', category: 'fruit', emoji: '🍓' },
    { id: '9-12-fruit-6', name: 'Watermelon', category: 'fruit', emoji: '🍉' },
    { id: '9-12-fruit-7', name: 'Pineapple', category: 'fruit', emoji: '🍍' },
    { id: '9-12-fruit-8', name: 'Mango', category: 'fruit', emoji: '🥭' },
    { id: '9-12-fruit-9', name: 'Coconut', category: 'fruit', emoji: '🥥' },
    { id: '9-12-fruit-10', name: 'Avocado', category: 'fruit', emoji: '🥑' },
    { id: '9-12-fruit-11', name: 'Melon', category: 'fruit', emoji: '🍈' },
    { id: '9-12-fruit-12', name: 'Tangerine', category: 'fruit', emoji: '🍊' },
    // Vegetables
    { id: '9-12-veg-1', name: 'Carrot', category: 'vegetable', emoji: '🥕' },
    { id: '9-12-veg-2', name: 'Broccoli', category: 'vegetable', emoji: '🥦' },
    { id: '9-12-veg-3', name: 'Tomato', category: 'vegetable', emoji: '🍅' },
    { id: '9-12-veg-4', name: 'Corn', category: 'vegetable', emoji: '🌽' },
    { id: '9-12-veg-5', name: 'Cucumber', category: 'vegetable', emoji: '🥒' },
    { id: '9-12-veg-6', name: 'Pepper', category: 'vegetable', emoji: '🫑' },
    { id: '9-12-veg-7', name: 'Mushroom', category: 'vegetable', emoji: '🍄' },
    { id: '9-12-veg-8', name: 'Pumpkin', category: 'vegetable', emoji: '🎃' },
    { id: '9-12-veg-9', name: 'Garlic', category: 'vegetable', emoji: '🧄' },
    { id: '9-12-veg-10', name: 'Ginger', category: 'vegetable', emoji: '🫚' },
    { id: '9-12-veg-11', name: 'Cabbage', category: 'vegetable', emoji: '🥬' },
    { id: '9-12-veg-12', name: 'Asparagus', category: 'vegetable', emoji: '🥒' },
    // Animals
    { id: '9-12-animal-1', name: 'Dog', category: 'animal', emoji: '🐕' },
    { id: '9-12-animal-2', name: 'Cat', category: 'animal', emoji: '🐈' },
    { id: '9-12-animal-3', name: 'Rabbit', category: 'animal', emoji: '🐰' },
    { id: '9-12-animal-4', name: 'Bird', category: 'animal', emoji: '🐦' },
    { id: '9-12-animal-5', name: 'Fish', category: 'animal', emoji: '🐟' },
    { id: '9-12-animal-6', name: 'Elephant', category: 'animal', emoji: '🐘' },
    { id: '9-12-animal-7', name: 'Lion', category: 'animal', emoji: '🦁' },
    { id: '9-12-animal-8', name: 'Tiger', category: 'animal', emoji: '🐯' },
    { id: '9-12-animal-9', name: 'Bear', category: 'animal', emoji: '🐻' },
    { id: '9-12-animal-10', name: 'Giraffe', category: 'animal', emoji: '🦒' },
    { id: '9-12-animal-11', name: 'Zebra', category: 'animal', emoji: '🦓' },
    { id: '9-12-animal-12', name: 'Koala', category: 'animal', emoji: '🐨' },
    // Vehicles
    { id: '9-12-vehicle-1', name: 'Car', category: 'vehicle', emoji: '🚗' },
    { id: '9-12-vehicle-2', name: 'Bike', category: 'vehicle', emoji: '🚲' },
    { id: '9-12-vehicle-3', name: 'Bus', category: 'vehicle', emoji: '🚌' },
    { id: '9-12-vehicle-4', name: 'Train', category: 'vehicle', emoji: '🚂' },
    { id: '9-12-vehicle-5', name: 'Airplane', category: 'vehicle', emoji: '✈️' },
    { id: '9-12-vehicle-6', name: 'Boat', category: 'vehicle', emoji: '⛵' },
    { id: '9-12-vehicle-7', name: 'Truck', category: 'vehicle', emoji: '🚚' },
    { id: '9-12-vehicle-8', name: 'Helicopter', category: 'vehicle', emoji: '🚁' },
    { id: '9-12-vehicle-9', name: 'Motorcycle', category: 'vehicle', emoji: '🏍️' },
    { id: '9-12-vehicle-10', name: 'Rocket', category: 'vehicle', emoji: '🚀' },
    { id: '9-12-vehicle-11', name: 'Scooter', category: 'vehicle', emoji: '🛴' },
    { id: '9-12-vehicle-12', name: 'Taxi', category: 'vehicle', emoji: '🚕' },
  ],
  '13-15': [
    // Fruits
    { id: '13-15-fruit-1', name: 'Apple', category: 'fruit', emoji: '🍎' },
    { id: '13-15-fruit-2', name: 'Banana', category: 'fruit', emoji: '🍌' },
    { id: '13-15-fruit-3', name: 'Orange', category: 'fruit', emoji: '🍊' },
    { id: '13-15-fruit-4', name: 'Grapes', category: 'fruit', emoji: '🍇' },
    { id: '13-15-fruit-5', name: 'Strawberry', category: 'fruit', emoji: '🍓' },
    { id: '13-15-fruit-6', name: 'Watermelon', category: 'fruit', emoji: '🍉' },
    { id: '13-15-fruit-7', name: 'Pineapple', category: 'fruit', emoji: '🍍' },
    { id: '13-15-fruit-8', name: 'Mango', category: 'fruit', emoji: '🥭' },
    { id: '13-15-fruit-9', name: 'Coconut', category: 'fruit', emoji: '🥥' },
    { id: '13-15-fruit-10', name: 'Avocado', category: 'fruit', emoji: '🥑' },
    { id: '13-15-fruit-11', name: 'Melon', category: 'fruit', emoji: '🍈' },
    { id: '13-15-fruit-12', name: 'Papaya', category: 'fruit', emoji: '🍈' },
    { id: '13-15-fruit-13', name: 'Dragon Fruit', category: 'fruit', emoji: '🐉' },
    { id: '13-15-fruit-14', name: 'Pomegranate', category: 'fruit', emoji: '🍎' },
    // Vegetables
    { id: '13-15-veg-1', name: 'Carrot', category: 'vegetable', emoji: '🥕' },
    { id: '13-15-veg-2', name: 'Broccoli', category: 'vegetable', emoji: '🥦' },
    { id: '13-15-veg-3', name: 'Tomato', category: 'vegetable', emoji: '🍅' },
    { id: '13-15-veg-4', name: 'Corn', category: 'vegetable', emoji: '🌽' },
    { id: '13-15-veg-5', name: 'Cucumber', category: 'vegetable', emoji: '🥒' },
    { id: '13-15-veg-6', name: 'Pepper', category: 'vegetable', emoji: '🫑' },
    { id: '13-15-veg-7', name: 'Mushroom', category: 'vegetable', emoji: '🍄' },
    { id: '13-15-veg-8', name: 'Pumpkin', category: 'vegetable', emoji: '🎃' },
    { id: '13-15-veg-9', name: 'Garlic', category: 'vegetable', emoji: '🧄' },
    { id: '13-15-veg-10', name: 'Ginger', category: 'vegetable', emoji: '🫚' },
    { id: '13-15-veg-11', name: 'Cabbage', category: 'vegetable', emoji: '🥬' },
    { id: '13-15-veg-12', name: 'Spinach', category: 'vegetable', emoji: '🥬' },
    { id: '13-15-veg-13', name: 'Beet', category: 'vegetable', emoji: '🥕' },
    { id: '13-15-veg-14', name: 'Celery', category: 'vegetable', emoji: '🥬' },
    // Animals
    { id: '13-15-animal-1', name: 'Dog', category: 'animal', emoji: '🐕' },
    { id: '13-15-animal-2', name: 'Cat', category: 'animal', emoji: '🐈' },
    { id: '13-15-animal-3', name: 'Rabbit', category: 'animal', emoji: '🐰' },
    { id: '13-15-animal-4', name: 'Bird', category: 'animal', emoji: '🐦' },
    { id: '13-15-animal-5', name: 'Fish', category: 'animal', emoji: '🐟' },
    { id: '13-15-animal-6', name: 'Elephant', category: 'animal', emoji: '🐘' },
    { id: '13-15-animal-7', name: 'Lion', category: 'animal', emoji: '🦁' },
    { id: '13-15-animal-8', name: 'Tiger', category: 'animal', emoji: '🐯' },
    { id: '13-15-animal-9', name: 'Bear', category: 'animal', emoji: '🐻' },
    { id: '13-15-animal-10', name: 'Giraffe', category: 'animal', emoji: '🦒' },
    { id: '13-15-animal-11', name: 'Zebra', category: 'animal', emoji: '🦓' },
    { id: '13-15-animal-12', name: 'Koala', category: 'animal', emoji: '🐨' },
    { id: '13-15-animal-13', name: 'Kangaroo', category: 'animal', emoji: '🦘' },
    { id: '13-15-animal-14', name: 'Dolphin', category: 'animal', emoji: '🐬' },
    // Vehicles
    { id: '13-15-vehicle-1', name: 'Car', category: 'vehicle', emoji: '🚗' },
    { id: '13-15-vehicle-2', name: 'Bike', category: 'vehicle', emoji: '🚲' },
    { id: '13-15-vehicle-3', name: 'Bus', category: 'vehicle', emoji: '🚌' },
    { id: '13-15-vehicle-4', name: 'Train', category: 'vehicle', emoji: '🚂' },
    { id: '13-15-vehicle-5', name: 'Airplane', category: 'vehicle', emoji: '✈️' },
    { id: '13-15-vehicle-6', name: 'Boat', category: 'vehicle', emoji: '⛵' },
    { id: '13-15-vehicle-7', name: 'Truck', category: 'vehicle', emoji: '🚚' },
    { id: '13-15-vehicle-8', name: 'Helicopter', category: 'vehicle', emoji: '🚁' },
    { id: '13-15-vehicle-9', name: 'Motorcycle', category: 'vehicle', emoji: '🏍️' },
    { id: '13-15-vehicle-10', name: 'Rocket', category: 'vehicle', emoji: '🚀' },
    { id: '13-15-vehicle-11', name: 'Scooter', category: 'vehicle', emoji: '🛴' },
    { id: '13-15-vehicle-12', name: 'Taxi', category: 'vehicle', emoji: '🚕' },
    { id: '13-15-vehicle-13', name: 'Ambulance', category: 'vehicle', emoji: '🚑' },
    { id: '13-15-vehicle-14', name: 'Fire Truck', category: 'vehicle', emoji: '🚒' },
    // Objects
    { id: '13-15-object-1', name: 'Book', category: 'object', emoji: '📚' },
    { id: '13-15-object-2', name: 'Ball', category: 'object', emoji: '⚽' },
    { id: '13-15-object-3', name: 'Pencil', category: 'object', emoji: '✏️' },
    { id: '13-15-object-4', name: 'Clock', category: 'object', emoji: '⏰' },
    { id: '13-15-object-5', name: 'Phone', category: 'object', emoji: '📱' },
    { id: '13-15-object-6', name: 'Computer', category: 'object', emoji: '💻' },
    { id: '13-15-object-7', name: 'Camera', category: 'object', emoji: '📷' },
    { id: '13-15-object-8', name: 'Guitar', category: 'object', emoji: '🎸' },
    { id: '13-15-object-9', name: 'Backpack', category: 'object', emoji: '🎒' },
    { id: '13-15-object-10', name: 'Umbrella', category: 'object', emoji: '☂️' },
    { id: '13-15-object-11', name: 'Watch', category: 'object', emoji: '⌚' },
    { id: '13-15-object-12', name: 'Glasses', category: 'object', emoji: '👓' },
    { id: '13-15-object-13', name: 'Key', category: 'object', emoji: '🔑' },
    { id: '13-15-object-14', name: 'Trophy', category: 'object', emoji: '🏆' },
  ],
};

// Session item counts per age group
export const SESSION_ITEM_COUNT: Record<AgeGroupKey, number> = {
  '3-5': 4,
  '6-8': 6,
  '9-12': 8,
  '13-15': 10,
};
