/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LocalizedText {
    portuguese: string;
    japanese: string;
    chinese: string;
    turkish: string;
    italian: string;
    spanish: string;
    german: string;
    french: string;
    russian: string;
    english: string;
}
export interface SimpleQuestion {
    question?: string;
    correctAnswer?: string;
    options: Array<string>;
}
export interface LogicPuzzle {
    question: LocalizedText;
    difficulty: bigint;
    answer: LocalizedText;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface ProblemSolving {
    correctOption: LocalizedText;
    scenario: LocalizedText;
    options: Array<LocalizedText>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface SimpleGame {
    name?: string;
    description?: string;
    ageGroup: AgeGroup;
}
export interface MemoryGame {
    patterns: string;
    difficulty: bigint;
    language: Language;
}
export interface ColoringTemplateWithData {
    id: string;
    template: ExternalBlob;
    category: ColoringCategory;
    ageGroup: AgeGroup;
}
export interface VisualRecognition {
    differences: bigint;
    language: Language;
    imageId: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum AgeGroup {
    threeToFive = "threeToFive",
    nineToTwelve = "nineToTwelve",
    thirteenToFifteen = "thirteenToFifteen",
    sixToEight = "sixToEight"
}
export enum ColoringCategory {
    characters = "characters",
    animals = "animals",
    objects = "objects"
}
export enum Language {
    portuguese = "portuguese",
    japanese = "japanese",
    chinese = "chinese",
    turkish = "turkish",
    italian = "italian",
    spanish = "spanish",
    german = "german",
    french = "french",
    russian = "russian",
    english = "english"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    getAllColoringTemplates(): Promise<Array<ColoringTemplateWithData>>;
    getColoringTemplateById(templateId: string): Promise<ColoringTemplateWithData | null>;
    getColoringTemplatesByAgeGroup(ageGroup: AgeGroup): Promise<Array<ColoringTemplateWithData>>;
    getColoringTemplatesByCategory(category: ColoringCategory): Promise<Array<ColoringTemplateWithData>>;
    getEncouragementMessage(level: bigint, language: Language): Promise<string>;
    getGames(ageGroup: string, language: Language): Promise<Array<SimpleGame>>;
    getLogicPuzzles(ageGroup: string): Promise<Array<LogicPuzzle>>;
    getMemoryGames(ageGroup: string): Promise<Array<MemoryGame>>;
    getProblemSolvingTasks(ageGroup: string): Promise<Array<ProblemSolving>>;
    getQuizQuestions(ageGroup: string, language: Language): Promise<Array<SimpleQuestion>>;
    getRandomSoundByCategory(categoryName: string): Promise<ExternalBlob | null>;
    getSoundByName(soundName: string): Promise<ExternalBlob | null>;
    getSoundCategories(): Promise<Array<string>>;
    getSoundsByCategory(categoryName: string): Promise<Array<[string, ExternalBlob]>>;
    getVisualRecognitionTasks(ageGroup: string): Promise<Array<VisualRecognition>>;
}
import type { AgeGroup as _AgeGroup, ColoringCategory as _ColoringCategory, ColoringTemplateWithData as _ColoringTemplateWithData, ExternalBlob as _ExternalBlob, Language as _Language, MemoryGame as _MemoryGame, SimpleGame as _SimpleGame, SimpleQuestion as _SimpleQuestion, VisualRecognition as _VisualRecognition, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async getAllColoringTemplates(): Promise<Array<ColoringTemplateWithData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllColoringTemplates();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllColoringTemplates();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getColoringTemplateById(arg0: string): Promise<ColoringTemplateWithData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getColoringTemplateById(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getColoringTemplateById(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getColoringTemplatesByAgeGroup(arg0: AgeGroup): Promise<Array<ColoringTemplateWithData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getColoringTemplatesByAgeGroup(to_candid_AgeGroup_n17(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getColoringTemplatesByAgeGroup(to_candid_AgeGroup_n17(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getColoringTemplatesByCategory(arg0: ColoringCategory): Promise<Array<ColoringTemplateWithData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getColoringTemplatesByCategory(to_candid_ColoringCategory_n19(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getColoringTemplatesByCategory(to_candid_ColoringCategory_n19(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEncouragementMessage(arg0: bigint, arg1: Language): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getEncouragementMessage(arg0, to_candid_Language_n21(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEncouragementMessage(arg0, to_candid_Language_n21(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getGames(arg0: string, arg1: Language): Promise<Array<SimpleGame>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGames(arg0, to_candid_Language_n21(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGames(arg0, to_candid_Language_n21(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLogicPuzzles(arg0: string): Promise<Array<LogicPuzzle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLogicPuzzles(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLogicPuzzles(arg0);
            return result;
        }
    }
    async getMemoryGames(arg0: string): Promise<Array<MemoryGame>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemoryGames(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemoryGames(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProblemSolvingTasks(arg0: string): Promise<Array<ProblemSolving>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProblemSolvingTasks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProblemSolvingTasks(arg0);
            return result;
        }
    }
    async getQuizQuestions(arg0: string, arg1: Language): Promise<Array<SimpleQuestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizQuestions(arg0, to_candid_Language_n21(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizQuestions(arg0, to_candid_Language_n21(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRandomSoundByCategory(arg0: string): Promise<ExternalBlob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRandomSoundByCategory(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRandomSoundByCategory(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSoundByName(arg0: string): Promise<ExternalBlob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSoundByName(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSoundByName(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSoundCategories(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSoundCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSoundCategories();
            return result;
        }
    }
    async getSoundsByCategory(arg0: string): Promise<Array<[string, ExternalBlob]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSoundsByCategory(arg0);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSoundsByCategory(arg0);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVisualRecognitionTasks(arg0: string): Promise<Array<VisualRecognition>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisualRecognitionTasks(arg0);
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisualRecognitionTasks(arg0);
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AgeGroup_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AgeGroup): AgeGroup {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ColoringCategory_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ColoringCategory): ColoringCategory {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
async function from_candid_ColoringTemplateWithData_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ColoringTemplateWithData): Promise<ColoringTemplateWithData> {
    return await from_candid_record_n10(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Language_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Language): Language {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_MemoryGame_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MemoryGame): MemoryGame {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_SimpleGame_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SimpleGame): SimpleGame {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_SimpleQuestion_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SimpleQuestion): SimpleQuestion {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_VisualRecognition_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VisualRecognition): VisualRecognition {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ColoringTemplateWithData]): Promise<ColoringTemplateWithData | null> {
    return value.length === 0 ? null : await from_candid_ColoringTemplateWithData_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    template: _ExternalBlob;
    category: _ColoringCategory;
    ageGroup: _AgeGroup;
}): Promise<{
    id: string;
    template: ExternalBlob;
    category: ColoringCategory;
    ageGroup: AgeGroup;
}> {
    return {
        id: value.id,
        template: await from_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.template),
        category: from_candid_ColoringCategory_n12(_uploadFile, _downloadFile, value.category),
        ageGroup: from_candid_AgeGroup_n14(_uploadFile, _downloadFile, value.ageGroup)
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: [] | [string];
    description: [] | [string];
    ageGroup: _AgeGroup;
}): {
    name?: string;
    description?: string;
    ageGroup: AgeGroup;
} {
    return {
        name: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.name)),
        description: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.description)),
        ageGroup: from_candid_AgeGroup_n14(_uploadFile, _downloadFile, value.ageGroup)
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    patterns: string;
    difficulty: bigint;
    language: _Language;
}): {
    patterns: string;
    difficulty: bigint;
    language: Language;
} {
    return {
        patterns: value.patterns,
        difficulty: value.difficulty,
        language: from_candid_Language_n30(_uploadFile, _downloadFile, value.language)
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    question: [] | [string];
    correctAnswer: [] | [string];
    options: Array<string>;
}): {
    question?: string;
    correctAnswer?: string;
    options: Array<string>;
} {
    return {
        question: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.question)),
        correctAnswer: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.correctAnswer)),
        options: value.options
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    differences: bigint;
    language: _Language;
    imageId: string;
}): {
    differences: bigint;
    language: Language;
    imageId: string;
} {
    return {
        differences: value.differences,
        language: from_candid_Language_n30(_uploadFile, _downloadFile, value.language),
        imageId: value.imageId
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_tuple_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _ExternalBlob]): Promise<[string, ExternalBlob]> {
    return [
        value[0],
        await from_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    characters: null;
} | {
    animals: null;
} | {
    objects: null;
}): ColoringCategory {
    return "characters" in value ? ColoringCategory.characters : "animals" in value ? ColoringCategory.animals : "objects" in value ? ColoringCategory.objects : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    threeToFive: null;
} | {
    nineToTwelve: null;
} | {
    thirteenToFifteen: null;
} | {
    sixToEight: null;
}): AgeGroup {
    return "threeToFive" in value ? AgeGroup.threeToFive : "nineToTwelve" in value ? AgeGroup.nineToTwelve : "thirteenToFifteen" in value ? AgeGroup.thirteenToFifteen : "sixToEight" in value ? AgeGroup.sixToEight : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    portuguese: null;
} | {
    japanese: null;
} | {
    chinese: null;
} | {
    turkish: null;
} | {
    italian: null;
} | {
    spanish: null;
} | {
    german: null;
} | {
    french: null;
} | {
    russian: null;
} | {
    english: null;
}): Language {
    return "portuguese" in value ? Language.portuguese : "japanese" in value ? Language.japanese : "chinese" in value ? Language.chinese : "turkish" in value ? Language.turkish : "italian" in value ? Language.italian : "spanish" in value ? Language.spanish : "german" in value ? Language.german : "french" in value ? Language.french : "russian" in value ? Language.russian : "english" in value ? Language.english : value;
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SimpleGame>): Array<SimpleGame> {
    return value.map((x)=>from_candid_SimpleGame_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MemoryGame>): Array<MemoryGame> {
    return value.map((x)=>from_candid_MemoryGame_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SimpleQuestion>): Array<SimpleQuestion> {
    return value.map((x)=>from_candid_SimpleQuestion_n33(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _ExternalBlob]>): Promise<Array<[string, ExternalBlob]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n37(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VisualRecognition>): Array<VisualRecognition> {
    return value.map((x)=>from_candid_VisualRecognition_n39(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ColoringTemplateWithData>): Promise<Array<ColoringTemplateWithData>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ColoringTemplateWithData_n9(_uploadFile, _downloadFile, x)));
}
function to_candid_AgeGroup_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AgeGroup): _AgeGroup {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_ColoringCategory_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ColoringCategory): _ColoringCategory {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_Language_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): _Language {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AgeGroup): {
    threeToFive: null;
} | {
    nineToTwelve: null;
} | {
    thirteenToFifteen: null;
} | {
    sixToEight: null;
} {
    return value == AgeGroup.threeToFive ? {
        threeToFive: null
    } : value == AgeGroup.nineToTwelve ? {
        nineToTwelve: null
    } : value == AgeGroup.thirteenToFifteen ? {
        thirteenToFifteen: null
    } : value == AgeGroup.sixToEight ? {
        sixToEight: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ColoringCategory): {
    characters: null;
} | {
    animals: null;
} | {
    objects: null;
} {
    return value == ColoringCategory.characters ? {
        characters: null
    } : value == ColoringCategory.animals ? {
        animals: null
    } : value == ColoringCategory.objects ? {
        objects: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): {
    portuguese: null;
} | {
    japanese: null;
} | {
    chinese: null;
} | {
    turkish: null;
} | {
    italian: null;
} | {
    spanish: null;
} | {
    german: null;
} | {
    french: null;
} | {
    russian: null;
} | {
    english: null;
} {
    return value == Language.portuguese ? {
        portuguese: null
    } : value == Language.japanese ? {
        japanese: null
    } : value == Language.chinese ? {
        chinese: null
    } : value == Language.turkish ? {
        turkish: null
    } : value == Language.italian ? {
        italian: null
    } : value == Language.spanish ? {
        spanish: null
    } : value == Language.german ? {
        german: null
    } : value == Language.french ? {
        french: null
    } : value == Language.russian ? {
        russian: null
    } : value == Language.english ? {
        english: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
